Repository IntersectMBO/cardano-cli, pull requests merged in 2024-02, with the labels that each got.

#527 Provide more detailed error upon missing policy id
  cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/TxCmdError.hs
Labels: Stale

#603 Add immutable tip parameter to conway queries
  .github/workflows/haskell.yml
  cardano-cli/src/Cardano/CLI/EraBased/Commands/Query.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs
  cardano-cli/src/Cardano/CLI/Legacy/Run/Query.hs
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_committee-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_constitution.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_drep-stake-distribution.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_drep-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_gov-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_kes-period-info.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_leadership-schedule.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_ledger-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_pool-params.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_pool-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_protocol-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_slot-number.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_stake-address-info.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_stake-distribution.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_stake-pools.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_stake-snapshot.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_tip.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_utxo.cli
Labels: enhancement

#610 Fix git revision reported by --version on nix build
  cardano-cli/src/Cardano/CLI/IO/GitRev.hs
  flake.nix
Labels: bug
