Repository IntersectMBO/cardano-cli, pull requests merged in 2024-11, with the labels that each got.

#951 Add anchor hash checks to `transaction build`
  cardano-cli/cardano-cli.cabal
  cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs
  cardano-cli/src/Cardano/CLI/EraBased/Transaction/HashCheck.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/TxCmdError.hs
Labels: DO NOT MERGE, next-update

#961 create-testnet-data: add option to create constitutional committee members
  cardano-cli/src/Cardano/CLI/EraBased/Commands/Genesis.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Genesis.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Genesis/CreateTestnetData.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Committee.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/GenesisCmdError.hs
  cardano-cli/test/cardano-cli-golden/Test/Golden/CreateTestnetData.hs
  cardano-cli/test/cardano-cli-golden/files/golden/conway/create-testnet-data.out
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/allegra_genesis_create-testnet-data.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/alonzo_genesis_create-testnet-data.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/babbage_genesis_create-testnet-data.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_genesis_create-testnet-data.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_genesis_create-testnet-data.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/mary_genesis_create-testnet-data.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/shelley_genesis_create-testnet-data.cli
Labels: next-update

#957 Remove direct dependencies from `ouroboros-*`
  cardano-cli/cardano-cli.cabal
  cardano-cli/src/Cardano/CLI/Byron/Tx.hs
  cardano-cli/src/Cardano/CLI/Byron/UpdateProposal.hs
  cardano-cli/src/Cardano/CLI/Byron/Vote.hs
  cardano-cli/src/Cardano/CLI/EraBased/Commands/Query.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Genesis.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Genesis/CreateTestnetData.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/GovernanceQueryError.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/QueryCmdError.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/QueryCmdLocalStateQueryError.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/TxCmdError.hs
Labels: next-update

#979 Allow and add warning for HTTP anchor-data
  cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/Actions.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Governance/DRep.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/StakePool.hs
  cardano-cli/src/Cardano/CLI/Parser.hs
  cardano-cli/src/Cardano/CLI/Run/Hash.hs
  cardano-cli/src/Cardano/CLI/Types/Common.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/HashCmdError.hs
Labels: enhancement
