Repository IntersectMBO/cardano-cli, pull requests merged in 2025-01, with the labels that each got.

#982 Move `genesis hash` to `hash genesis-file`
  cardano-cli/src/Cardano/CLI/Commands/Hash.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Genesis.hs
  cardano-cli/src/Cardano/CLI/Legacy/Options.hs
  cardano-cli/src/Cardano/CLI/Options/Hash.hs
  cardano-cli/src/Cardano/CLI/Run/Hash.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/HashCmdError.hs
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/allegra_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/allegra_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/alonzo_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/alonzo_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/babbage_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/babbage_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/hash_genesis-file.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/legacy_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/legacy_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/mary_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/mary_genesis_hash.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/shelley_genesis.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/shelley_genesis_hash.cli
Labels: enhancement

#977 Add datums and scripts to `friendlyTxImpl`
  cardano-cli/src/Cardano/CLI/Json/Friendly.hs
  cardano-cli/test/cardano-cli-golden/files/golden/alonzo/signed-transaction-view.out
  cardano-cli/test/cardano-cli-golden/files/golden/alonzo/transaction-view.out
  cardano-cli/test/cardano-cli-golden/files/golden/babbage/transaction-view-metadata-detailedschema.out
  cardano-cli/test/cardano-cli-golden/files/golden/babbage/transaction-view-metadata-noschema.out
  cardano-cli/test/cardano-cli-golden/files/golden/babbage/transaction-view-redeemer.out
  cardano-cli/test/cardano-cli-golden/files/golden/conway/tx-proposal.out.json
  cardano-cli/test/cardano-cli-golden/files/golden/conway/tx-three-votes-view.out.json
Labels: enhancement

#980 Misc refactors in pretty printing and replacing unnecessary functions
  cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/PlutusScriptDecodeError.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/ScriptDataError.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/ScriptDecodeError.hs
Labels: Stale

#972 Add certificates to CLI interface in `compatible transaction-sign`
  cardano-cli/cardano-cli.cabal
  cardano-cli/src/Cardano/CLI/Compatible/Transaction.hs
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/compatible_allegra_transaction_signed-transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/compatible_alonzo_transaction_signed-transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/compatible_babbage_transaction_signed-transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/compatible_conway_transaction_signed-transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/compatible_mary_transaction_signed-transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/compatible_shelley_transaction_signed-transaction.cli
  cardano-cli/test/cardano-cli-test/Test/Cli/Shelley/Transaction/Compatible/Build.hs
  flake.nix
Labels: next-update

#1020 Adapt to removal of some patterns in API
  cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs
  cardano-cli/src/Cardano/CLI/Json/Friendly.hs
Labels: next-update
