Repository IntersectMBO/cardano-cli, pull requests merged in 2025-02, with the labels that each got.

#1036 Add the ratify-state query
  cardano-cli/src/Cardano/CLI/EraBased/Commands/Query.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Query.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_query_ratify-state.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_query.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_query_ratify-state.cli
Labels: next-update

#1048 Organise hash and ping commands
  cardano-cli/src/Cardano/CLI/Commands.hs
  cardano-cli/src/Cardano/CLI/Options.hs
  cardano-cli/src/Cardano/CLI/Options/Ping.hs
  cardano-cli/test/cardano-cli-golden/Test/Golden/Help.hs
  cardano-cli/test/cardano-cli-golden/files/golden/base_help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/ping.cli
Labels: documentation

#1060 Fix haddocks for StakeAddressInfoData
  cardano-cli/src/Cardano/CLI/EraBased/Run/Query.hs
Labels: documentation

#1031 Add command to calculate plutus script costs from an already constructed transaction
  cardano-cli/cardano-cli.cabal
  cardano-cli/src/Cardano/CLI/EraBased/Commands/Transaction.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Common.hs
  cardano-cli/src/Cardano/CLI/EraBased/Options/Transaction.hs
  cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs
  cardano-cli/src/Cardano/CLI/Types/Errors/TxCmdError.hs
  cardano-cli/src/Cardano/CLI/Types/Output.hs
  cardano-cli/test/cardano-cli-golden/files/golden/help.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/allegra_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/allegra_transaction_calculate-plutus-script-cost.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/alonzo_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/alonzo_transaction_calculate-plutus-script-cost.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/babbage_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/babbage_transaction_build.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/babbage_transaction_calculate-plutus-script-cost.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_transaction_build.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/conway_transaction_calculate-plutus-script-cost.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_transaction_build.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/latest_transaction_calculate-plutus-script-cost.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/mary_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/mary_transaction_calculate-plutus-script-cost.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/shelley_transaction.cli
  cardano-cli/test/cardano-cli-golden/files/golden/help/shelley_transaction_calculate-plutus-script-cost.cli
Labels: enhancement
